### ISSUE TITLE
checkpointing in optimize.py (GBM Space4) 

### ISSUE THREAD

**Issue by jdakka** [yngtodd/constellation#1]
I ran the optimize.py script in the `gbm/space4` file but ran into this error: 

```
File "optimize.py", line 119, in <module>
    main()
  File "optimize.py", line 112, in main
    checkpoints=True)
TypeError: 'module' object is not callable
```

**Comment by yngtodd** [comment]
Hmm.. is that the full stack trace? If not, would you mind posting the full trace?

It looks like it has something to do with the checkpointing. Have we tested a case where hyperspace was using `checkpoints=True` before?

**Comment by jdakka** [comment]
What I posted is the full stack trace. We have not tested for `checkpoints=True` before

**Comment by yngtodd** [comment]
That's interesting. With vanilla HyperSpace, when `checkpoints=True`, each MPI rank would write their results to `args.results_dir`. Maybe we should try with `checkpoints=False`.

**Comment by jdakka** [comment]
Same error popped up when I set `checkpoints=False` in `optimize.py` 
```
/home/dakka/miniconda3/envs/ve_hyperspace/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "optimize.py", line 119, in <module>
    main()
  File "optimize.py", line 112, in main
    checkpoints=False)
TypeError: 'module' object is not callable
```

**Comment by yngtodd** [comment]
Hmmm can you show me how you are running it?

**Comment by jdakka** [comment]
```
#!/bin/bash
#SBATCH -N 16
#SBATCH -p RM
#SBATCH -t 5:00:00
#SBATCH --ntasks-per-node 28
#SBATCH -A mc3bggp


export PATH="/home/dakka/miniconda3/bin:$PATH"
export LD_LIBRARY_PATH="/home/dakka/miniconda3/lib:$LD_LIBRARY_PATH"
module load mpi/gcc_openmpi
source activate ve_hyperspace

mpirun -n 16 python optimize.py --data_path /home/dakka/hyperspace/constellation/constellation/data/fashion --results_dir /home/dakka/hyperspace/constellation/constellation/gbm/space4/results_local_data

```

**Comment by yngtodd** [comment]
Cool. Let me give it a couple tests on my end.

**Comment by jdakka** [comment]
Hey Todd, let me know if you need any additional details or test runs on `Bridges`. In the meanwhile, I would like to run a 3-stage analysis pipeline with and without data staging to give you a sense of the overheads. Would it be ok to run the `example.py` script from the `hyperspace` repo? I can repeat that executable 3x and add in the `MNIST` data just for data staging purposes, nothing related to file inputs.

**Comment by yngtodd** [comment]
Will do! I am currently testing the constellation code on SummitDev ad Titan. Just got to get our environments on those machines ironed out bit first. 

The `example.py` is a regression problem, but I could put together a classification example using MNIST pretty quickly. Would Pytorch be a hassle to get running on Bridges?

**Comment by yngtodd** [comment]
I'm not quite sure what is causing `optimize.py` to fail when running on Bridges. Just tested on Titan and everything is OK. Arvind mentioned that Bridges is similar to how Titan is setup, but there must be some detail that I am missing. 

Here is how I am running things on Titan:
```
#!/bin/bash -l
#PBS -A CSC264
#PBS -l walltime=2:00:00
#PBS -l nodes=16
#PBS -N Constellation 
#PBS -j oe


CSC264=/lustre/atlas/proj-shared/csc264
export SINGULARITYENV_MPICH_GNI_MALLOC_FALLBACK=1

cd /lustre/atlas/proj-shared/csc264/yngtodd/constellation/constellation/gbm/space4

aprun -n 16 -N 1 $CSC264/singularity/basic_py36/bin/python optimize.py --data_path /lustre/atlas/proj-shared/csc264/yngtodd/constellation/constellation/data/fashion --results_dir results
```

**Comment by jdakka** [comment]
It seems to be my environment because I tried running the example.py again and it didn't work. I'm going to create a new env and run some tests.

**Comment by yngtodd** [comment]
Cool, let me know if there is anything I can do on my end. When I retested on Titan I was able to pip install constellation from source. I had been wondering if something there was causing the issue.

**Comment by jdakka** [comment]
Ok I created a new VE, module purged, and reloaded the necessary openMPI compiler (note that we have to use a gcc compiler, as the RADICAL-Cybertools require only gcc). I was able to get it working. I will try a few more test runs with this VE to make sure it is stable. I ran the `optimize.py` with 2 hyperparameters interactively. 

```
(ve_hyperspace) [dakka@r007 space2]$ mpirun -n 4 python optimize.py --data_path /home/dakka/hyperspace/constellation/constellation/data/fashion --results_dir /home/dakka/hyperspace/constellation/constellation/gbm/space4/results_local_data
Iteration No: 1 started. Evaluating function at random point.
      Iter       Train Loss   Remaining Time 
      Iter       Train Loss   Remaining Time 
      Iter       Train Loss   Remaining Time 
      Iter       Train Loss   Remaining Time 
         1       70632.6156           73.07m
         1       70632.6156           46.19m
         2       59402.7693           71.91m
         2       59402.7693           44.94m
         3       51613.6098           71.06m
         3       51613.6098           43.90m
         1       66646.0668          247.34m
         1       66646.2997          156.21m
         4       45644.2018           70.19m
         4       45644.2018           42.80m
         5       40803.4306           41.97m
         5       40803.4306           69.45m
         6       36855.5357           41.15m
         6       36855.5357           68.67m
         7       33584.9930           40.34m
         7       33584.9930           67.96m
         2       54045.1285          253.55m
         2       54045.1962          158.40m
         8       30819.2371           39.51m
         8       30819.2371           67.12m
         9       28480.7417           38.71m
         9       28480.7417           66.28m

```

Quite a high training loss ;)

**Comment by yngtodd** [comment]
Great! Is that running this example: https://github.com/yngtodd/constellation/blob/master/constellation/gbm/space2/optimize.py? 

And that's an old trick, if the training loss is horrible at the beginning, it is more impressive to see how far it comes at the end. Also, I should add that code comes with no guarantees. haha

**Comment by jdakka** [comment]
@yngtodd Thanks! Yes I was running `/space2`. Can you give me an estimate on how long each optimization is supposed to run so I can configure my wall-time properly? If it helps, this is the output for a 2 param optimization that took 60 minutes.

```
[dakka@br005 unit.000000]$ cat STDOUT
Iteration No: 1 started. Evaluating function at random point.
      Iter       Train Loss   Remaining Time 
      Iter       Train Loss   Remaining Time 
      Iter       Train Loss   Remaining Time 
      Iter       Train Loss   Remaining Time 
         1       70632.6156           73.17m
         1       70632.6156           45.69m
         2       59402.7693           72.45m
         2       59402.7693           45.17m
         3       51613.6098           71.75m
         3       51613.6098           44.22m
         1       66645.7833          239.73m
         1       66646.2376          154.63m
         4       45644.2018           43.21m
         4       45644.2018           71.33m
         5       40803.4306           42.47m
         5       40803.4306           70.38m
         6       36855.5357           41.65m
         6       36855.5357           69.65m
         2       54044.9879          247.62m
         2       54045.5534          155.76m
         7       33584.9930           40.90m
         7       33584.9930           68.75m
         8       30819.2371           67.71m
         8       30819.2371           40.13m
         9       28480.7417           66.84m
         9       28480.7417           39.21m
        10       26449.2315           66.03m
        10       26449.2315           38.33m
         3       45301.2448          250.34m
         3       45297.8106          155.48m
         4       38654.5574          250.07m
         4       38643.7792          153.65m
         5       33343.8776          248.65m
         5       33326.0343          150.83m
        20       15660.6816           30.10m
        20       15660.6816           57.93m
         6       29055.2664          245.92m
         6       29042.3959          148.27m
         7       25489.0639          244.13m
         7       25507.2245          145.60m
         8       22552.7487          241.93m
         8       22556.8095          142.88m
        30       11643.2644           21.88m
        30       11643.2644           49.54m
         9       20078.3606          238.94m
         9       20088.7027          139.97m
        10       17968.8226          136.88m
        10       17960.8805          236.27m
        40        9449.8643           13.67m
        40        9449.8643           41.12m
        50        8017.2108            5.60m
        50        8017.2108           32.93m
      Iter       Train Loss   Remaining Time 
         1       69168.6131           68.41m
        60        6952.5371           24.80m
         2       57435.5021           67.16m
         3       49210.1058           66.37m
         4       43050.9014           65.00m
         5       38065.3232           63.84m
         6       34025.8585           62.65m
         7       30717.8217           61.31m
         8       27887.7985           60.02m
        70        6162.9702           16.73m
        20        7239.6378          200.99m
         9       25489.5303           58.91m
        20        7272.3020          105.37m
        10       23417.3822           57.62m

```

**Comment by yngtodd** [comment]
Do you mean for each iteration of the optimization? HyperSpace should print out how long each iteration takes.

**Comment by jdakka** [comment]
It does print out but the durations are quite variable as expected remaining time jumps around and I'm not sure what kind of wall-time to expect. I'm running the `/space2/optimize.py` script on Bridges and I set the wall time to 5 hours, not sure how long it will run for.

**Comment by yngtodd** [comment]
Oh man, that is a good question. I'm not sure how long that will take. 

I know we talked about trying to change the setting for *checkpoints* in `hyperdrive`. If that doesn't cause problems on Bridges, then having that turned on would let us save the intermittent results at each step of the optimization. That way, if the wall time catches us, we can resume where we left off.

**Comment by jdakka** [comment]
* I ran the `/space2/optimize.py` example running with Fashion MNIST data for 5 hours. In the last few iterations just before wall time was reached, the output log shows:

```
40        1386.5135           63.06m
50       11073.7260            7.74m
60        9994.3456            2.21m
20       12503.2825           62.94m
Iter       Train Loss   Remaining Time
1       74796.0021           20.87m
2       65005.8399           20.46m
```

* I could run it for longer but I think the expected runtime is still fluctuating. Given that I set `checkpoint=True` can we agree on a duration that will work for you and is supported by the `RCT`? In the past, I ran jobs using `RCT` that are approximately 48 hours long but on a different machine. Given that the max wall-time on Bridges is 48 hours, I could run some benchmarks that test for stability. Let me know what would be the best way to proceed. 

* Another idea I wanted to bounce was having a method that will resubmit the hyperspace-RCT job to the batch system as soon as wall time is reached, which would enable the analysis to continue from the last checkpoint. What do you think?

**Comment by yngtodd** [comment]
I like the idea of being able to resubmit the job as soon as a previous run finishes. With Titan we handle that with some simple bash scripts to handle filesystem's queue. Here is an example:

Titan submission script:
```
#!/bin/bash -l
#PBS -A CSC264
#PBS -l walltime=2:00:00
#PBS -l nodes=16
#PBS -N A2C 
#PBS -j oe

CSC264=/lustre/atlas/proj-shared/csc264
export SINGULARITYENV_MPICH_GNI_MALLOC_FALLBACK=1

cd $CSC264/yngtodd/hyperpoints/hyperpoints/a2c/hyperspace

aprun -n 16 $CSC264/singularity/basic_py36/bin/python optimize.py --results_dir results --checkpoint checkpoint
```
Bash script that checks if the previous run started, and then runs 15 more iterations after the previous has finished:
```
JOB_ID=`qsub titan.pbs`

for i in {1..16}
do
  JOB_ID=`qsub -W depend=afterok:$JOB_ID titan.pbs`
done
```

**Comment by yngtodd** [comment]
I guess we could let the jobs run for 24 or 48 hours with checkpointing to see how far they get. Now that we see that it runs with real data, what is it that we would like to test, the scaling numbers as we increase the parameter search space?

**Comment by jdakka** [comment]
Quick update `OpenMPI` was stable for my last few runs. I was able to get through 6 iterations of `space4/optimize.py` for 2 hours with RCT :) Will test now for 5 hours and continue scaling up from there. 

For a 3-stage analysis pipeline, I was thinking to run the `space4/` example 3x. What would you think is a good duration? Should we see if we can do 5 hours per analysis back-to-back? Just to get some preliminary data...

**Comment by jdakka** [comment]
The 5-hour run was stable, I'll run a few more trials at this length (to get some error bars on duration and overheads)  and then scale up to 24 hours.
